
// This file has been generated by the GUI designer. Do not modify.
namespace ToDoManager.UserInterface
{
	internal partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action OptionsAction;
		
		private global::Gtk.Frame MainFrame;
		
		private global::Gtk.Table FrameTable;
		
		private global::Gtk.ScrolledWindow GtkScrolledMessageWindow;
		
		private global::Gtk.TextView MesssageTextView;
		
		private global::Gtk.ScrolledWindow GtkScrolledTableWindow;
		
		private global::Gtk.Table MainTable;
		
		private global::Gtk.ScrolledWindow GtkScrolledImportantNotUrgentWindow;
		
		private global::Gtk.VBox ImportantNotUrgentVBox;
		
		private global::Gtk.ScrolledWindow GtkScrolledImportantUrgentWindow;
		
		private global::Gtk.VBox ImportantUrgentVBox;
		
		private global::Gtk.ScrolledWindow GtkScrolledNotImportantNotUrgentWindow;
		
		private global::Gtk.VBox NotImportantNotUrgentVBox;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.VBox NotImportantUrgentVBox;
		
		private global::Gtk.Label ImportantLabel;
		
		private global::Gtk.Label NotImportantLabel;
		
		private global::Gtk.Label NotUrgentLabel;
		
		private global::Gtk.SpinButton spinbutton1;
		
		private global::Gtk.Label UrgentLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToDoManager.UserInterface.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.OptionsAction = new global::Gtk.Action ("OptionsAction", global::Mono.Unix.Catalog.GetString ("Options"), null, null);
			this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Test");
			w1.Add (this.OptionsAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "ToDoManager.UserInterface.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			// Container child ToDoManager.UserInterface.MainWindow.Gtk.Container+ContainerChild
			this.MainFrame = new global::Gtk.Frame ();
			this.MainFrame.Name = "MainFrame";
			this.MainFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.MainFrame.LabelYalign = 0F;
			// Container child MainFrame.Gtk.Container+ContainerChild
			this.FrameTable = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.FrameTable.Name = "FrameTable";
			this.FrameTable.RowSpacing = ((uint)(1));
			this.FrameTable.ColumnSpacing = ((uint)(1));
			// Container child FrameTable.Gtk.Table+TableChild
			this.GtkScrolledMessageWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledMessageWindow.Name = "GtkScrolledMessageWindow";
			this.GtkScrolledMessageWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledMessageWindow.Gtk.Container+ContainerChild
			this.MesssageTextView = new global::Gtk.TextView ();
			this.MesssageTextView.CanFocus = true;
			this.MesssageTextView.Name = "MesssageTextView";
			this.MesssageTextView.CursorVisible = false;
			this.MesssageTextView.Justification = ((global::Gtk.Justification)(2));
			this.MesssageTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledMessageWindow.Add (this.MesssageTextView);
			this.FrameTable.Add (this.GtkScrolledMessageWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.FrameTable [this.GtkScrolledMessageWindow]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child FrameTable.Gtk.Table+TableChild
			this.GtkScrolledTableWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledTableWindow.Name = "GtkScrolledTableWindow";
			this.GtkScrolledTableWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledTableWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w4 = new global::Gtk.Viewport ();
			w4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.MainTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.MainTable.Name = "MainTable";
			this.MainTable.RowSpacing = ((uint)(6));
			this.MainTable.ColumnSpacing = ((uint)(6));
			this.MainTable.BorderWidth = ((uint)(1));
			// Container child MainTable.Gtk.Table+TableChild
			this.GtkScrolledImportantNotUrgentWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledImportantNotUrgentWindow.Name = "GtkScrolledImportantNotUrgentWindow";
			this.GtkScrolledImportantNotUrgentWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledImportantNotUrgentWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport4.Gtk.Container+ContainerChild
			this.ImportantNotUrgentVBox = new global::Gtk.VBox ();
			this.ImportantNotUrgentVBox.Name = "ImportantNotUrgentVBox";
			this.ImportantNotUrgentVBox.Homogeneous = true;
			this.ImportantNotUrgentVBox.Spacing = 6;
			w5.Add (this.ImportantNotUrgentVBox);
			this.GtkScrolledImportantNotUrgentWindow.Add (w5);
			this.MainTable.Add (this.GtkScrolledImportantNotUrgentWindow);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledImportantNotUrgentWindow]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			// Container child MainTable.Gtk.Table+TableChild
			this.GtkScrolledImportantUrgentWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledImportantUrgentWindow.Name = "GtkScrolledImportantUrgentWindow";
			this.GtkScrolledImportantUrgentWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledImportantUrgentWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w9 = new global::Gtk.Viewport ();
			w9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport3.Gtk.Container+ContainerChild
			this.ImportantUrgentVBox = new global::Gtk.VBox ();
			this.ImportantUrgentVBox.Name = "ImportantUrgentVBox";
			this.ImportantUrgentVBox.Homogeneous = true;
			this.ImportantUrgentVBox.Spacing = 6;
			w9.Add (this.ImportantUrgentVBox);
			this.GtkScrolledImportantUrgentWindow.Add (w9);
			this.MainTable.Add (this.GtkScrolledImportantUrgentWindow);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledImportantUrgentWindow]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			// Container child MainTable.Gtk.Table+TableChild
			this.GtkScrolledNotImportantNotUrgentWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledNotImportantNotUrgentWindow.Name = "GtkScrolledNotImportantNotUrgentWindow";
			this.GtkScrolledNotImportantNotUrgentWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledNotImportantNotUrgentWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w13 = new global::Gtk.Viewport ();
			w13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.NotImportantNotUrgentVBox = new global::Gtk.VBox ();
			this.NotImportantNotUrgentVBox.Name = "NotImportantNotUrgentVBox";
			this.NotImportantNotUrgentVBox.Homogeneous = true;
			this.NotImportantNotUrgentVBox.Spacing = 6;
			w13.Add (this.NotImportantNotUrgentVBox);
			this.GtkScrolledNotImportantNotUrgentWindow.Add (w13);
			this.MainTable.Add (this.GtkScrolledNotImportantNotUrgentWindow);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledNotImportantNotUrgentWindow]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			// Container child MainTable.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w17 = new global::Gtk.Viewport ();
			w17.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.NotImportantUrgentVBox = new global::Gtk.VBox ();
			this.NotImportantUrgentVBox.Name = "NotImportantUrgentVBox";
			this.NotImportantUrgentVBox.Homogeneous = true;
			this.NotImportantUrgentVBox.Spacing = 6;
			w17.Add (this.NotImportantUrgentVBox);
			this.GtkScrolledWindow.Add (w17);
			this.MainTable.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledWindow]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.ImportantLabel = new global::Gtk.Label ();
			this.ImportantLabel.Name = "ImportantLabel";
			this.ImportantLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Important");
			this.ImportantLabel.Wrap = true;
			this.ImportantLabel.Justify = ((global::Gtk.Justification)(2));
			this.MainTable.Add (this.ImportantLabel);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.MainTable [this.ImportantLabel]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.NotImportantLabel = new global::Gtk.Label ();
			this.NotImportantLabel.Name = "NotImportantLabel";
			this.NotImportantLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Not \nImportant");
			this.NotImportantLabel.Justify = ((global::Gtk.Justification)(2));
			this.MainTable.Add (this.NotImportantLabel);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.MainTable [this.NotImportantLabel]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.NotUrgentLabel = new global::Gtk.Label ();
			this.NotUrgentLabel.Name = "NotUrgentLabel";
			this.NotUrgentLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Not \nUrgent");
			this.NotUrgentLabel.Wrap = true;
			this.NotUrgentLabel.Justify = ((global::Gtk.Justification)(2));
			this.MainTable.Add (this.NotUrgentLabel);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.MainTable [this.NotUrgentLabel]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.spinbutton1 = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10;
			this.spinbutton1.ClimbRate = 1;
			this.spinbutton1.Numeric = true;
			this.MainTable.Add (this.spinbutton1);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.MainTable [this.spinbutton1]));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.UrgentLabel = new global::Gtk.Label ();
			this.UrgentLabel.Name = "UrgentLabel";
			this.UrgentLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Urgent");
			this.UrgentLabel.Wrap = true;
			this.UrgentLabel.Justify = ((global::Gtk.Justification)(2));
			this.MainTable.Add (this.UrgentLabel);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.MainTable [this.UrgentLabel]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			w4.Add (this.MainTable);
			this.GtkScrolledTableWindow.Add (w4);
			this.FrameTable.Add (this.GtkScrolledTableWindow);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.FrameTable [this.GtkScrolledTableWindow]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			this.MainFrame.Add (this.FrameTable);
			this.Add (this.MainFrame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 990;
			this.DefaultHeight = 503;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
